name: Update LeetCode and GfG Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch LeetCode Stats
      run: |
        curl -s https://leetcode-stats-api.herokuapp.com/mayraju > leetcode.json
        echo "LeetCode solved problems: $(jq '.totalSolved' leetcode.json)" >> README.md

    - name: Commit and Push
      run: |
        git config --global user.name Mayraju
        git config --global user.email mayraju777@gmail.com
        git add README.md
        git commit -m "Update solved problems stats"
        git push
